# -*- coding: utf-8 -*-
"""Emit engine/assets/i18n.js from _i18n_tables.json (chrome + games tables)."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ORDER = ["zh", "es", "pt", "ru", "ja", "ko", "de", "fr", "id"]

with open(os.path.join(HERE, "_i18n_tables.json"), encoding="utf-8") as f:
    TABS = json.load(f)

HEADER = '''/* NeonPlay i18n — site-wide runtime language switcher.
   Priority: ?lang= > localStorage(np_lang) > navigator.language > en
   Wired regions: nav, hall (hero/sections/cards/spotlight), landing + variant
   headers, game titles/taglines/controls, footer, about/privacy/contact/404.
   Per-game FAQ & how-to step bodies stay English (deep tier). English is baked
   into the HTML and doubles as the en dictionary: a null translation keeps the
   original node untouched. Generated by engine/_gen_i18n.py — edit tables, not this file. */
(function(){
"use strict";
var LANGS=[
  {code:"en",   label:"English"},
  {code:"zh",   label:"简体中文"},
  {code:"es",   label:"Español"},
  {code:"pt",   label:"Português"},
  {code:"ru",   label:"Русский"},
  {code:"ja",   label:"日本語"},
  {code:"ko",   label:"한국어"},
  {code:"de",   label:"Deutsch"},
  {code:"fr",   label:"Français"},
  {code:"id",   label:"Bahasa Indonesia"}
];
var T={
'''

FOOTER = '''};
function detect(){
  var q=new URLSearchParams(location.search).get("lang");
  if(q&&LANGS.some(function(l){return l.code===q;}))return q;
  var s=null;try{s=localStorage.getItem("np_lang");}catch(e){}
  if(s&&LANGS.some(function(l){return l.code===s;}))return s;
  var nl=(navigator.languages&&navigator.languages[0])||navigator.language||"en";
  var pref=function(p){return nl.indexOf(p)===0;};
  if(pref("zh"))return "zh";
  if(pref("es"))return "es";
  if(pref("pt"))return "pt";
  if(pref("ru"))return "ru";
  if(pref("ja"))return "ja";
  if(pref("ko"))return "ko";
  if(pref("de"))return "de";
  if(pref("fr"))return "fr";
  if(pref("id"))return "id";
  return "en";
}
var lang=detect();
window.npLang=function(){return lang;};
window.npSetLang=function(code){
  try{localStorage.setItem("np_lang",code);}catch(e){}
  location.reload();
};
window.npT=function(key){
  var d=T[lang]||{};
  return Object.prototype.hasOwnProperty.call(d,key)?d[key]:null;
};
function subst(el,v){
  v=v.replace(/\\{year\\}/g,String(new Date().getFullYear()));
  var g=el.getAttribute("data-i18n-game");
  if(g!=null)v=v.replace(/\\{game\\}/g,g);
  return v;
}
function apply(){
  var nodes=document.querySelectorAll("[data-i18n]");
  for(var i=0;i<nodes.length;i++){
    var el=nodes[i],v=npT(el.getAttribute("data-i18n"));
    if(v==null)continue;
    v=subst(el,v);
    if(el.hasAttribute("data-i18n-html"))el.innerHTML=v;
    else if(el.children.length===0)el.textContent=v;
  }
  ["placeholder","aria-label","title"].forEach(function(at){
    var ns=document.querySelectorAll("[data-i18n-"+at+"]");
    for(var j=0;j<ns.length;j++){
      var t=npT(ns[j].getAttribute("data-i18n-"+at));
      if(t!=null)ns[j].setAttribute(at,t);
    }
  });
}
function switcher(){
  var nav=document.querySelector(".site-head nav");
  if(!nav)return;
  var b=document.createElement("button");
  b.id="lang-btn";b.textContent="🌐 "+lang.toUpperCase();
  b.style.cssText="background:transparent;border:1px solid rgba(255,255,255,.25);color:inherit;border-radius:8px;padding:4px 10px;font-size:.85rem;cursor:pointer";
  var dd=document.createElement("div");
  dd.style.cssText="position:absolute;right:0;top:110%;background:#141a35;border:1px solid #2b3564;border-radius:10px;padding:6px;display:none;flex-direction:column;min-width:150px;z-index:50;box-shadow:0 8px 24px rgba(0,0,0,.5)";
  LANGS.forEach(function(l){
    var o=document.createElement("div");
    o.textContent=l.label;
    o.style.cssText="padding:7px 12px;border-radius:6px;cursor:pointer;font-size:.9rem"+(l.code===lang?";color:#22d3ee":"");
    o.addEventListener("click",function(e){e.stopPropagation();window.npSetLang(l.code);});
    o.addEventListener("mouseenter",function(){o.style.background="#232b52";});
    o.addEventListener("mouseleave",function(){o.style.background="transparent";});
    dd.appendChild(o);
  });
  var wrap=document.createElement("div");
  wrap.style.cssText="position:relative;margin-left:8px";
  wrap.appendChild(b);wrap.appendChild(dd);
  b.addEventListener("click",function(e){e.stopPropagation();dd.style.display=dd.style.display==="flex"?"none":"flex";});
  document.addEventListener("click",function(){dd.style.display="none";});
  nav.appendChild(wrap);
}
function boot(){
  apply();
  switcher();
  document.documentElement.lang=lang;
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);
else boot();
})();
'''


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


parts = [HEADER]
for li, lang in enumerate(ORDER):
    entries = [tuple(x) for x in TABS["chrome"][lang]]
    for slug, title, tag, ct in TABS["games"][lang]:
        entries.append(("game.%s.title" % slug, title))
        entries.append(("game.%s.tag" % slug, tag))
        entries.append(("game.%s.controls" % slug, ct))
    parts.append(lang + ":{\n")
    for ki, (k, v) in enumerate(entries):
        comma = "," if ki < len(entries) - 1 else ""
        parts.append(' "%s":"%s"%s\n' % (k, esc(v), comma))
    parts.append("}" + ("," if li < len(ORDER) - 1 else "") + "\n")
parts.append(FOOTER)
out = "".join(parts)
with open(os.path.join(HERE, "assets", "i18n.js"), "w", encoding="utf-8", newline="\n") as f:
    f.write(out)
print("written", len(out), "chars,", sum(len(TABS["games"][l]) for l in ORDER), "games/lang")
