# -*- coding: utf-8 -*-
"""Game catalog for the /games/ section.

Each entry: slug, title, h1, desc (meta), tagline, emoji, howto, faqs,
controls. The playable build lives in engine/assets/games/<slug>/play(.html|/)
and is copied verbatim to docs/games/<slug>/play(...)/ — games are self-contained
and iframe-embedded into the landing page.
"""

GAMES = [
    {
        "slug": "neon-tide",
        "title": "Play Neon Tide — Free Online Neon Arcade Shooter",
        "h1": "Neon Tide",
        "tagline": "Ride the neon tide — a synthwave arcade shooter with procedural sound, waves of glowing enemies and boss pressure.",
        "desc": "Play Neon Tide free online: a synthwave neon arcade shooter with waves of glowing enemies, procedural music and endless escalating pressure. No download, no sign-up.",
        "emoji": "🌊",
        "accent": "#22d3ee",
        "play": "play/",  # directory build
        "howto": [
            "Move with the mouse or arrow keys — your ship follows on the lower half of the screen.",
            "Hold to fire; dodging matters as much as shooting because enemies return fire in patterns.",
            "Survive escalating waves, chase the score multiplier, and beat your personal best.",
        ],
        "controls": "Mouse / touch to move, hold to shoot. Keyboard: arrow keys.",
        "faqs": [
            ("Is Neon Tide free?",
             "Yes — it runs entirely in your browser for free, with no download, account or payment. It is an original game built by the NeonPlay team."),
            ("Does it work on mobile?",
             "Yes. The game auto-scales to any screen and supports touch: drag to move your ship, it fires automatically while you hold."),
            ("Who made Neon Tide?",
             "We did — it is an exclusive NeonPlay original, with every sound and effect generated in code (no asset files)."),
            ("Does the game track me?",
             "No. The game runs 100% locally in your browser; your scores never leave your device."),
        ],
    },
    {
        "slug": "snake",
        "title": "Play Snake Online — Free Classic Snake Game",
        "h1": "Snake",
        "tagline": "The timeless snake game: eat, grow, don't bite yourself. One more run is always one turn away.",
        "desc": "Play the classic Snake game free online. Arrow keys, WASD or swipe on mobile. Eat apples, grow longer, avoid your own tail — instant play, no download.",
        "emoji": "🐍",
        "accent": "#4ade80",
        "howto": [
            "Press any arrow key (or swipe on mobile) to start — the snake moves on its own once started.",
            "Steer into the red apples: every apple makes you one segment longer and raises your score.",
            "Avoid walls and your own tail — the game ends the moment you crash, then restart instantly.",
        ],
        "controls": "Arrow keys / WASD, or swipe on touch screens.",
        "faqs": [
            ("How do you win at Snake?",
             "Snake has no final win — you win by beating your high score. The classic technique is to coil in a spiral: keep your body along the edges so the center stays open for emergency turns."),
            ("Is this the same Snake as on old Nokia phones?",
             "Same game concept — eat, grow, don't crash. This version is an original browser implementation with smooth controls, mobile swipe support and instant restart."),
            ("Does it work on a phone?",
             "Yes — swipe anywhere on the board to steer. The board scales to fit any screen size."),
            ("Are my scores saved?",
             "Your best score is kept in memory while the tab is open; nothing is stored on our side or on your device after you leave."),
        ],
    },
    {
        "slug": "2048",
        "title": "Play 2048 Online — Free Number Puzzle Game",
        "h1": "2048",
        "tagline": "Slide, merge, double. A deceptively simple number puzzle that eats hours — reach the 2048 tile.",
        "desc": "Play 2048 free online. Swipe or use arrow keys to merge tiles and reach 2048. Original clean implementation, instant play, works on desktop and mobile.",
        "emoji": "🔢",
        "accent": "#fbbf24",
        "howto": [
            "Swipe or press arrow keys to slide every tile one step in that direction.",
            "When two tiles with the same number touch, they merge into one tile of double value.",
            "A new tile appears after each move — keep big numbers in one corner and build toward 2048.",
        ],
        "controls": "Arrow keys / WASD, or swipe on touch screens.",
        "faqs": [
            ("What is the 2048 world record?",
             "Reaching the 2048 tile is the classic goal; expert players keep going to 4096 and beyond. Scores above 20,000 are considered very strong; the theoretical maximum tile on a 4×4 board is 131,072."),
            ("What is the best strategy for 2048?",
             "Pick one corner and never move your biggest tile out of it — most players keep it bottom-right and only use three directions. Build a descending 'snake chain' of tiles so merges cascade."),
            ("Is this the original 2048?",
             "This is our own clean-room implementation of the 2048 rules (the game concept was created by Gabriele Cirulli in 2014). No ads inside the board, instant restarts."),
            ("Does it work offline?",
             "Yes — once the page has loaded, the game runs entirely in your browser with no connection needed."),
        ],
    },
    {
        "slug": "memory-pairs",
        "title": "Memory Pairs — Free Online Matching Card Game",
        "h1": "Memory Pairs",
        "tagline": "Flip, remember, match. The classic concentration card game — train your working memory in two minutes.",
        "desc": "Play Memory Pairs free online: the classic concentration matching game with 8 emoji pairs. Flip two cards, find all pairs in as few moves as you can.",
        "emoji": "🧠",
        "accent": "#c084fc",
        "howto": [
            "Click any card to flip it, then click a second one.",
            "If the two cards match, they stay face up; if not, they flip back after a moment.",
            "Remember what you saw — clear all 8 pairs in the fewest moves possible.",
        ],
        "controls": "Click / tap cards.",
        "faqs": [
            ("What is the fewest moves to win Memory Pairs?",
             "With 8 pairs and perfect memory, 8 moves (16 flips) is the theoretical minimum — every flip after the first pair of each turn must match. Typical casual wins land around 14–20 moves."),
            ("Does this game actually improve memory?",
             "Concentration-style games train visual working memory — the 'where did I see that' skill. Regular play improves your strategy (scanning in rows) and short-term recall."),
            ("Is it suitable for kids?",
             "Yes — no timers, no fail states, big friendly cards. It is a calm game; kids and grandparents play it the same way."),
            ("Can I play on a phone?",
             "Yes, tap cards directly — the board resizes to fit your screen."),
        ],
    },
    {
        "slug": "tic-tac-toe",
        "title": "Tic Tac Toe Online — Play Free vs Computer or a Friend",
        "h1": "Tic Tac Toe",
        "tagline": "X's, O's and one unbeatable robot. The three-in-a-row classic — now with a minimax AI you can actually beat (sometimes).",
        "desc": "Play Tic Tac Toe free online against a smart computer AI or a friend in 2-player mode. Instant play in your browser, works on desktop and mobile.",
        "emoji": "⭕",
        "howto": [
            "Tap any square (or press keys 1–9) to place your X — you always start.",
            "The computer replies instantly with strong play; line up three in a row — across, down or diagonally — to win.",
            "Switch to 2-player mode to pass and play with a friend on the same screen.",
        ],
        "controls": "Click / tap squares, or number keys 1–9.",
        "faqs": [
            ("Can you beat the computer at Tic Tac Toe?",
             "Our AI plays near-perfect minimax strategy with a small dose of randomness — it never falls for the classic double-threat traps, but it leaves the door open just often enough. About one in five games is winnable with sharp play."),
            ("Is Tic Tac Toe solved?",
             "Yes — with perfect play from both sides, Tic Tac Toe is always a draw. That's why the interesting question is spotting your opponent's mistake first, and why our AI deliberately isn't 100% perfect."),
            ("How do I always win Tic Tac Toe?",
             "Against imperfect opponents: take the center first, then create a fork — two threats at once. A fork forces a loss because your opponent can only block one line."),
            ("Is it free and private?",
             "Completely. The game runs in your browser with no sign-up, no ads inside the board, and nothing is uploaded — scores reset when you leave."),
        ],
    },
    {
        "slug": "breakout",
        "title": "Play Breakout Online — Free Brick Breaker Game",
        "h1": "Breakout",
        "tagline": "One ball, one paddle, a wall of glowing bricks — the arcade classic that never gets old.",
        "desc": "Play Breakout free online: smash every neon brick with one ball and a paddle you control by mouse, touch or keyboard. Level up, chase high scores, no download or sign-up.",
        "emoji": "🧱",
        "howto": [
            "Move the paddle with your mouse, finger or arrow keys — keep the ball alive.",
            "Launch with a tap, click or Space, then clear all six rows of bricks to advance.",
            "Each cleared wall starts a faster level; you get three lives per run, so aim carefully.",
        ],
        "controls": "Mouse / touch to move the paddle, tap or click to launch. Keyboard: arrow keys + Space.",
        "faqs": [
            ("Is Breakout free to play here?",
             "Yes — it runs entirely in your browser, no download, no account and no payment. It is an original NeonPlay implementation of the arcade classic."),
            ("Does Breakout work on a phone?",
             "Yes. Drag anywhere on the screen to slide the paddle and tap to launch — the board scales to any screen size in portrait or landscape."),
            ("What happens when I clear all the bricks?",
             "You advance to the next level: the ball gets faster and the wall resets. Your score carries over, and tougher two-hit bricks stay at the top rows."),
            ("How is my score calculated?",
             "Each brick is worth more in higher rows — up to 60 points per brick. Three lives per run, and your best runs come from keeping the ball angle steep and controlled."),
        ],
    },
    {
        "slug": "minesweeper",
        "title": "Play Minesweeper Online — Free Classic Mine Game",
        "h1": "Minesweeper",
        "tagline": "Ten mines, ninety-one tiles, zero room for luck. The logic puzzle that ate the 90s — reborn for your phone.",
        "desc": "Play the classic Minesweeper free online: 9x9 board with 10 mines, first click is always safe, tap to reveal and long-press to flag. No download, works on desktop and mobile.",
        "emoji": "💣",
        "howto": [
            "Tap a tile to reveal it — the first tap is always safe, and numbers show how many mines touch that tile.",
            "Long-press a tile (or right-click, or turn on flag mode) to mark mines you have deduced.",
            "Reveal every safe tile to win; hitting a single mine ends the run, so let logic lead.",
        ],
        "controls": "Tap / click to reveal, long-press or right-click to flag. Flag-mode button for precision play.",
        "faqs": [
            ("Is the first click in Minesweeper always safe?",
             "Yes — mines are placed after your first reveal, and the first tap plus its neighbors are guaranteed mine-free, so every game starts with a real opening."),
            ("How do I flag a mine on mobile?",
             "Press and hold a tile for about half a second, or tap the flag-mode button above the board and then tap tiles — both mark or unmark a suspected mine."),
            ("What do the numbers mean in Minesweeper?",
             "A number tells you exactly how many of the eight surrounding tiles hide a mine. Cross-referencing overlapping numbers is how you deduce which tiles are safe."),
            ("Is this Minesweeper free and private?",
             "Completely free with no sign-up. Everything runs locally in your browser — your games, times and flags never leave your device."),
        ],
    },
    {
        "slug": "flappy-dash",
        "title": "Play Flappy Dash Online — Free One-Tap Flying Game",
        "h1": "Flappy Dash",
        "tagline": "One tap to fly, one touch to die. Thread the neon gates and chase your best through a synthwave skyline.",
        "desc": "Play Flappy Dash free online: a one-tap neon flying arcade game. Guide your glider through endless gates with perfect timing. Instant play on desktop and mobile, no download.",
        "emoji": "🚀",
        "howto": [
            "Tap the screen, click, or press Space to flap — each tap gives one upward boost against gravity.",
            "Thread the glowing gates: every gate you pass is one point, and gaps tighten as your score climbs.",
            "One touch of a gate or the ground ends the run — find your rhythm and chase your best score.",
        ],
        "controls": "Tap / click / Space to flap. That's the whole game — mastery is timing.",
        "faqs": [
            ("Is Flappy Dash free?",
             "Yes — it runs entirely in your browser with no download, account or payment. It is an original NeonPlay arcade game with procedurally drawn neon visuals."),
            ("Why is Flappy Dash so hard?",
             "By design: gravity is constant and each tap is a fixed boost, so success is pure rhythm. Gaps shrink as your score rises, keeping every run tense."),
            ("Does it work on mobile?",
             "Yes — tap anywhere on the screen to flap. The game scales to any screen and runs at full speed on modern phones."),
            ("Is my best score saved?",
             "Your best score is kept for the session so you can chase it immediately. Nothing is stored on our servers — gameplay stays on your device."),
        ],
    },
    {
        "slug": "reflex-rush",
        "play": "play/",
        "title": "Play Reflex Rush — Free Online Reaction Time Test Game with Ranks & Daily Challenge",
        "h1": "Reflex Rush",
        "tagline": "How many milliseconds are your reflexes? Tap shrinking neon rings before they vanish, chain combos up to ×4 and turn your 30-second average into a rank from Bronze to Legend.",
        "desc": "Play Reflex Rush free online: a reaction time test game that scores your speed in milliseconds. Tap targets before they shrink away, build combo multipliers, earn ranks from Bronze to Legend and take the same daily challenge as players worldwide. No download, no sign-up.",
        "emoji": "⚡",
        "accent": "#00e5ff",
        "howto": [
            "Neon rings pop up and shrink fast — tap one before it vanishes and the game logs that reaction in milliseconds.",
            "Score per hit grows as you get faster, and chained hits multiply it: 3 in a row is ×2, 6 is ×3, 10 is ×4. Misses and mistaps reset the combo.",
            "Every run lasts 30 seconds; your average reaction time decides your rank, from Bronze up to Legend (under 200ms).",
            "Play the Daily Challenge for a seeded board identical worldwide, keep a day streak going, and share your score card in one tap.",
        ],
        "controls": "Tap / click the rings; tapping empty space is a miss. Keyboard: Space start, Enter strike target, P pause, M mute.",
        "faqs": [
            ("What is Reflex Rush?",
             "A free reaction-time arcade game: neon targets shrink fast, tap them before they vanish, chain combos, and turn your milliseconds into a rank from Bronze to Legend."),
            ("What's a good reaction time?",
             "Average visual reaction is around 210-280ms; consistent sub-230ms is elite (that's Diamond+ here). Your rank is computed from your 30-second average."),
            ("Is there a daily challenge?",
             "Yes — a seeded board identical for everyone worldwide each day, with streak tracking and milestone forgiveness so one busy day doesn't break your run."),
            ("Can I play on mobile?",
             "Yes, tap-first design with full keyboard accessibility; free, no download, no account. Scores save on your device and share as a card in one tap."),
        ],
    },
    {
        "slug": "brickstorm",
        "title": "Play Brickstorm — Free Neon Brick Breaker Roguelite with Upgrades",
        "h1": "Brickstorm",
        "tagline": "Catch balls, smash brick waves, pick upgrades — Breakout meets Vampire Survivors in this neon roguelite.",
        "desc": "Play Brickstorm free online: a neon brick-breaker roguelite with upgrade builds, infinite waves and combo scoring. One-tap controls on desktop and mobile, no download.",
        "emoji": "🧱",
        "howto": [
            "Move the paddle left and right to catch falling balls — they auto-launch upward.",
            "Smash the advancing brick wall to earn XP; bricks glow brighter as their HP increases.",
            "Collect XP orbs to level up and choose one of three random upgrades that stack for the run.",
        ],
        "controls": "Drag / arrow keys / AD to move the paddle. Balls auto-launch — just position and survive.",
        "faqs": [
            ("What is Brickstorm?",
             "A free browser roguelite that fuses brick-breaker physics with Vampire-Survivors-style upgrade builds. Catch balls, smash waves of neon bricks, and pick from three random upgrades each level."),
            ("How do upgrades work?",
             "Destroyed bricks drop XP orbs that auto-attract to your paddle. Fill the XP bar and the game pauses, offering three random upgrades — multiball, damage, speed, pierce or wider paddle — that stack for the rest of the run."),
            ("Can I play Brickstorm on mobile?",
             "Yes. Touch-drag to move the paddle, fully responsive canvas, no download or sign-up needed. Keyboard (arrow keys / AD) and mouse also supported on desktop."),
            ("What's the best upgrade strategy?",
             "Most players take Multiball first (each ball deals full damage), then Damage or Pierce. Keep your combo alive by hitting brick clusters quickly — the multiplier caps at 3×."),
        ],
        "variants": [
            {
                "kw_slug": "ball-x-pit-browser-alternative",
                "title": "Ball x Pit Browser Alternative — Brickstorm (Free, No Download)",
                "desc": "Looking for a Ball x Pit browser alternative? Brickstorm mixes survival breakout waves with roguelite level-up picks — free, no download, no account.",
                "intro": [
                    "Ball x Pit welded pinball-style ball physics to roguelite progression and became the game everyone wants to play one more run of. Brickstorm takes the same addictive skeleton — balls that keep hitting, bricks that keep coming, levels that let you stack power — and rebuilds it natively for the browser, so the run starts the second the page loads instead of the second your download finishes.",
                    "The loop reads like a love letter to Ball x Pit fans: a relentless cascade of numbered brick waves pushes down toward your paddle, every broken brick drops XP orbs for you to catch, and each level-up deals a three-card choice — MULTIBALL to flood the screen, DAMAGE to punch through tanky rows, PIERCE to tunnel through clusters, PADDLE to widen your catch, SPEED to make everything reckless. A combo multiplier (up to 3×) rewards players who keep chains alive instead of sniping single bricks.",
                    "Where Brickstorm differs is friction, not depth: there is nothing to install, nothing to launch, no account wall and no paywall — it is a single HTML page with the whole game in it. It runs on the same cheap laptop you have open for work, it supports touch and keyboard on the same screen, and the interface ships in English and Chinese. If your appetite for Ball x Pit outlived your patience for its install queues, this is the five-minute fix.",
                ],
                "faqs": [
                    ("Is Brickstorm really free like Ball x Pit?",
                     "Yes — completely free with no account, no download and no paywall. The whole game is one web page: open it, tap a mode and play. There are no energy systems or timers gating your runs."),
                    ("How is Brickstorm different from Ball x Pit?",
                     "Ball x Pit adds ball fusion and an inventory meta between runs; Brickstorm keeps the survival-breakout core — descending waves, XP orbs, three-card level-up picks, a combo multiplier — as a pure browser experience with zero install friction. Think of it as the same genre itch in a smaller, instant-loading package."),
                    ("Does it work on a phone or a school laptop?",
                     "Both. The game auto-scales to any screen, supports swipe and drag on touch, and because everything runs locally in the browser it performs fine on low-end hardware and locked-down machines with nothing but a browser installed."),
                ],
            },
            {
                "kw_slug": "games-like-ball-x-pit-free",
                "title": "Games Like Ball x Pit (Free, In Your Browser) — Brickstorm & More",
                "desc": "Free browser games like Ball x Pit: merge-driven Brickstorm, classic Breakout, merge-puzzle 2048 and the idle ball-builder Idle Neon Breaker — all instant-play.",
                "intro": [
                    "If Ball x Pit hooked you, what you actually fell for is a stack of three overlapping pleasures: balls that keep flying, numbers that keep growing, and builds that feel smarter every run. The good news is that a browser is enough to chase all three — no storefront, no download queue, no GPU requirement. Here is what to play, all free on this site.",
                    "Brickstorm is the closest match: a survival breakout where waves descend and never stop, XP orbs drop from every break, and each level-up offers a three-card roguelite pick (multiball, pierce, damage, paddle width, ball speed). A combo multiplier up to 3× punishes passive play. Idle Neon Breaker takes the ball-builder fantasy in the opposite direction — balls bounce by themselves, bricks merge 2048-style and double on a timer, and your offline earnings accumulate at full rate with no cap while the tab is closed.",
                    "For the number-growth side of Ball x Pit, the site 2048 is the reset-your-brain classic, and Breakout covers the pure paddle-and-ball ancestor. All four games run on the same engine philosophy: one page, instant load, English and Chinese, no accounts. Bookmark the hall page — new games are added regularly and land in the RSS feed the day they ship.",
                ],
                "faqs": [
                    ("What games are similar to Ball x Pit but free?",
                     "Brickstorm (survival breakout with roguelite upgrades) is the nearest free match here; Idle Neon Breaker covers the ball-builder side with 2048-style merges, and classic Breakout and 2048 round out the number-growth itch. Every one of them loads instantly in a browser tab."),
                    ("Can I play without installing anything?",
                     "Yes. Each game is a self-contained web page — there is no launcher, no download and no plug-in. You can close the tab mid-run on Brickstorm, or leave Idle Neon Breaker running to farm offline earnings."),
                    ("Do these games work on mobile?",
                     "They are built mobile-first: touch targets are sized for thumbs, the boards scale to the screen, and Brickstorm paddle follows your finger. Desktop keyboards work too — arrow keys steer every paddle game."),
                ],
            },
            {
                "kw_slug": "vampire-survivors-breakout-online",
                "title": "Vampire Survivors-Style Breakout Online — Brickstorm Survival Waves",
                "desc": "The auto-attack survival loop, rebuilt as a breakout: balls that never stop, descending waves, and a three-card build choice on every level-up. Free in your browser.",
                "intro": [
                    "Vampire Survivors defined a genre by automating the shooting and keeping only the decisions: steer your character, vacuum the XP, and pick the upgrade that turns your build monstrous. Brickstorm applies exactly that philosophy to a paddle game. Your ball is the auto-attack — it never stops moving and never asks you to press a fire button. Your paddle is the character — positioning is the entire skill expression. The descending brick waves are the swarm.",
                    "The survival loop maps one-to-one: bricks shatter into glowing XP orbs that drift toward your paddle; catch enough and you level up, pausing the chaos for a three-card choice — flood the screen with MULTIBALL, punch through armor with DAMAGE, or thread clusters with PIERCE. Meanwhile a timer pushes new waves down every eight seconds, so the board steadily thickens like a survivors minute count climbing. A combo multiplier rewards the moment your build comes online and starts clearing screens instead of bricks.",
                    "Runs are tuned for browser-sized sessions: three lives, an escalation that reaches dense multi-row waves, and a game-over screen that tracks your best wave and score against your own record. It is the survivors fantasy compressed into a tab that is already open — no download, English or Chinese, touch or keyboard.",
                ],
                "faqs": [
                    ("Is Brickstorm really like Vampire Survivors?",
                     "Structurally yes: automatic attacks (the bouncing ball), XP you collect for level-ups, three-choice upgrade drafting, escalating waves and a combo economy that rewards snowballing. The skill layer swaps character steering for paddle positioning."),
                    ("How long is a run?",
                     "Most runs last a few minutes — the wave pressure ends them quickly if your build falls behind. The HUD tracks your best wave and best score locally, so the natural loop is one more run to beat your own record."),
                    ("What upgrades can I pick?",
                     "Each level-up offers three of: MULTIBALL (extra ball), DAMAGE +1, SPEED +20%, PIERCE (hit through extra bricks), and PADDLE +25% width. Stacking them is where runs go from survival to screen-clearing."),
                ],
            },
        ],    },
    {
        "slug": "neon-block-jam",
        "title": "Play Neon Block Jam — Free Color Block Puzzle (No Timer)",
        "h1": "Neon Block Jam",
        "tagline": "Slide neon blocks through matching color gates — no timer, no lives, just pure puzzle zen with unlimited undo.",
        "desc": "Play Neon Block Jam free online: a relaxing color block sliding puzzle with 10 levels, unlimited undo and no timer. Slide neon blocks through matching gates — instant play on desktop and mobile.",
        "emoji": "🟦",
        "howto": [
            "Tap a block to select it, then drag along its axis to slide — it snaps to the grid one cell at a time.",
            "Blocks can only exit through their matching color gate on the outer wall; different-colored blocks block the gate.",
            "Clear every block from the board to win. Finish at or under par moves for 3 stars, with unlimited free undo.",
        ],
        "controls": "Tap / click to select, drag to slide. Keyboard: arrow keys to move cursor, Enter to confirm. U = undo, R = reset.",
        "faqs": [
            ("Is there a timer in Neon Block Jam?",
             "No — deliberately timer-free with unlimited free undo. The only score is a move count vs par for stars, so you can think as long as you want without anxiety."),
            ("How do the color gates work?",
             "Each gate on the outer wall has a color. A block of the same color can pass through and vanish. Blocks of any other color are blocked by the gate wall — that's the puzzle: figure out the right order."),
            ("Can I play on my phone?",
             "Yes. Touch-drag controls, responsive layout, works in any modern browser. No download, no sign-up, no ads interrupting your puzzle."),
            ("How do I get 3 stars on a level?",
             "Finish at or under par moves. Tip: clear the blocks that block other blocks' gates first, and keep the center of the board open as long as possible."),
        ],
    },

    {
        "slug": "connect-four",
        "title": "Play Connect Four Online — Free Strategy Board Game vs AI",
        "h1": "Connect Four",
        "tagline": "Drop discs, build a line of four, block your opponent — the classic strategy game reimagined with neon visuals and a built-in AI.",
        "desc": "Play Connect Four free online against a smart AI or a friend. Drop discs to build four in a row — horizontal, vertical or diagonal. No download, instant play.",
        "emoji": "🔴",
        "howto": [
            "Click any column to drop your disc — red discs are yours, the AI plays pink.",
            "Build a line of four (horizontal, vertical or diagonal) before the AI does.",
            "Block the AI's attempts while building your own threat — think two moves ahead.",
        ],
        "controls": "Click / tap a column to drop your disc. The AI responds instantly.",
        "faqs": [
            ("Is Connect Four free to play here?",
             "Yes — it runs entirely in your browser with no download, account or payment. Play against our built-in AI or pass-and-play with a friend."),
            ("How does the AI work?",
             "Our AI checks for immediate wins and blocks your threats, with a touch of randomness to keep games interesting. It plays a strong but beatable game."),
            ("Can I play with a friend?",
             "Yes — switch to 2-player mode to pass and play on the same screen. Red and blue discs alternate turns."),
            ("What's the best opening move?",
             "The center column is statistically the strongest — it participates in more potential lines than any other column."),
        ],
    },
    {
        "slug": "idle-neon-breaker",
        "play": "play/",
        "title": "Idle Neon Breaker — Idle Brick Breaker with 2048 Merges (No Forced Ads)",
        "h1": "Idle Neon Breaker",
        "tagline": "An idle brick breaker where numbered bricks merge 2048-style and double while you watch — balls bounce and break on their own, offline progress is unlimited, and there are no forced ads.",
        "desc": "Free browser idle game: balls bounce and break numbered bricks on their own; bricks merge 2048-style and double over time; buy ball, damage, speed and coin upgrades and chase your highest brick. Full offline progress with no cap, autosave, no accounts, no forced ads.",
        "emoji": "💫",
        "howto": [
            "Balls bounce by themselves and damage bricks — each hit lowers a brick's number; at 0 it shatters into coins.",
            "Every 20 seconds bricks merge 2048-style: equal numbers combine and double (2+2→4, 4+4→8).",
            "Spend coins in the shop: more balls, more damage per hit, faster balls, bigger coin payouts.",
            "Close the tab any time — your coins keep earning at full rate offline, with no cap. Come back and claim.",
        ],
        "controls": "Zero controls required — the game plays itself. Tap the shop cards to buy upgrades.",
        "faqs": [
            ("What is Idle Neon Breaker?",
             "A free browser idle game: balls bounce and break numbered bricks on their own; bricks merge 2048-style and double over time; you buy upgrades and watch numbers explode. It runs in any browser — no download, no account."),
            ("Does it earn while I'm away?",
             "Yes. Offline progress is full-rate with no cap — close the tab, come back, claim everything at once. No 'come back every 2 hours' nonsense."),
            ("Are there forced ads or paywalls?",
             "No forced ads, ever. No accounts, no paywalls; progress saves automatically in your browser via localStorage."),
            ("What's the goal?",
             "Grow your highest brick: 2 → 4 → 8 → 16 and beyond. Keep firepower ahead of the merges and chase the record."),
        ],
    },
    {
        "slug": "neon-alchemy",
        "play": "play/",
        "title": "Neon Alchemy — Free Element Combining Game with Daily Puzzle (No AI, Works Everywhere)",
        "h1": "Neon Alchemy",
        "tagline": "Combine Water, Fire, Earth and Electric to discover 42 neon elements — from Steam to Cyberpunk. Handcrafted recipes, a daily global puzzle, zero AI, instant load.",
        "desc": "Free browser element-combining game: start with Water, Fire, Earth and Electric, discover 42 neon elements with handcrafted recipes, and take on the daily global puzzle board. No AI, no download, no account, progress saves automatically.",
        "emoji": "🧪",
        "howto": [
            "Tap two element chips to combine them — Water + Fire becomes Steam, and 38 handcrafted recipes lead from the basics to Cyberpunk.",
            "Every discovery unlocks new combinations and fills your collection wall — track your progress out of 42 elements.",
            "Take the daily puzzle: one handcrafted board per day, identical worldwide — reach the target element using only the limited pool.",
            "Your discoveries save automatically. Reset the collection any time for a fresh one-run challenge.",
        ],
        "controls": "Tap or click two element chips to combine. Keyboard: Tab + Enter works too.",
        "faqs": [
            ("What is Neon Alchemy?",
             "A free browser crafting game: combine Water, Fire, Earth and Electric to discover 42 neon elements, from Steam to Cyberpunk. No download, no account, and it loads instantly on any device."),
            ("Is there a daily challenge?",
             "Yes. One handcrafted puzzle board per day, identical for everyone worldwide, with a shareable result — Wordle-style. Boards rotate by date and limit which elements you can use."),
            ("Does it use AI like Infinite Craft?",
             "No. All recipes are handcrafted and built-in, so it loads instantly, works on school or office networks, and no discovery is ever wrong or random."),
            ("Is my progress saved?",
             "Yes. Your collection and daily completions save automatically in your browser via localStorage. You can reset the collection from inside the game for a fresh start."),
        ],
    },
    {
        "slug": "neon-block-blast",
        "title": "Block Blast Online Free — Neon Block Blast (No Ads, No Timer, Daily Challenge)",
        "h1": "Neon Block Blast",
        "tagline": "The classic block-blast puzzle, cleaned up: drag neon shapes onto an 8×8 board, clear lines, chase combos — no timer, no forced ads, plus a same-board daily challenge.",
        "desc": "Free online block puzzle: drag neon shapes onto an 8×8 grid and clear full rows or columns. Classic 19-shape set, combo scoring, no gravity, no timer, no forced ads. A daily challenge gives every player the same shape sequence — beat yesterday's best.",
        "emoji": "🧩",
        "howto": [
            "Drag one of the three neon shapes onto the 8×8 board — no gravity, blocks stay exactly where you drop them.",
            "Fill a full row or column to clear it. Clearing several lines at once multiplies your score.",
            "Placement scores the shape's cell count; chains and multi-line clears stack combos fast.",
            "When none of the three shapes fit anywhere, the run ends — try the daily challenge for a same-board global run.",
        ],
        "controls": "Drag with mouse or touch. Keyboard: Tab to pick a shape, arrows to move, Enter to drop.",
        "faqs": [
            ("Is Neon Block Blast free to play?",
             "Yes — it runs entirely in your browser with no download, account or forced ads. No interstitials interrupt your run, ever."),
            ("How does the daily challenge work?",
             "Every day all players get the same seeded shape sequence. Your daily best is stored per date, so you can compare against yesterday and chase a new record."),
            ("Is there a timer or gravity?",
             "No. Blocks stay exactly where you drop them and nothing falls — the only pressure is the board filling up. It is a pure spatial-planning puzzle."),
            ("How is scoring calculated?",
             "Placing a shape scores its cell count. Each cleared line adds 10 points, with multipliers for clearing several lines at once and a combo streak for consecutive clears."),
        ],
    },
    {
        "slug": "word-hive",
        "play": "play/",
        "title": "Word Hive — Free Unlimited Word Grouping Puzzle (Connections-Style, Built-in Hints)",
        "h1": "Word Hive",
        "tagline": "16 words hide 4 groups of four. Find the connections before 4 mistakes — with built-in three-level hints, a daily board, a 10-puzzle library and endless zen shuffle.",
        "desc": "Free unlimited word grouping puzzle in the Connections style: 16 words, 4 hidden groups, trap words and a difficulty curve. Three-level built-in hints, daily global board, puzzle library and endless shuffle. No account, no ads, plays in any browser.",
        "emoji": "🐝",
        "howto": [
            "Tap four words that share a connection, then press Submit.",
            "Correct groups reveal a colored banner and leave the board; wrong guesses cost one of four lives.",
            "Close but wrong? The game tells you when you are one word away — use it to adjust.",
            "Stuck? Open the hint ladder: reveal a category, a word, or solve a whole group. Or shuffle into endless zen mode.",
        ],
        "controls": "Tap words to select (up to 4), then Submit. Keyboard: Tab/arrows + Enter, S shuffle, H hint, U deselect.",
        "faqs": [
            ("What is Word Hive?",
             "A free word puzzle: 16 words hide 4 groups of four that share a connection. Find them all before 4 mistakes. No account, plays in any browser."),
            ("Is it unlimited?",
             "Yes: a featured daily board, a 10-puzzle library, and endless shuffle mode — no subscription, unlike some daily word games' archives."),
            ("What if I'm stuck?",
             "Built-in three-level hints reveal a category, a word, or a whole group. No leaving the page, no ads, no shame — using hints just marks your result."),
            ("Can I play on mobile?",
             "Yes: tap-friendly grid, keyboard supported, progress saves automatically; share your result with emoji like you're used to."),
        ],
    },
    {
        "slug": "neon-pop",
        "play": "play/",
        "title": "Play Neon Pop — Free Online One-Tap Block Popping Puzzle",
        "h1": "Neon Pop",
        "tagline": "One thumb is all you need — tap connected neon gems, ride 2-second combo chains up to ×5 and hunt the perfect clear.",
        "desc": "Play Neon Pop free online: a one-hand, tap-only neon block puzzle. Pop groups of 2+ connected gems, score exponentially with group size, chain combos up to ×5 and clear the whole board for a +2000 bonus. No download, no sign-up.",
        "emoji": "✨",
        "accent": "#ff2d95",
        "howto": [
            "Tap any group of 2 or more connected gems of the same color — they pop instantly and everything above falls down.",
            "Score grows with the square of the group size: a 10-gem pop pays 25× a 2-gem pop, so hunt the biggest cluster before you commit.",
            "Pop again within 2 seconds to build a chain multiplier up to ×5 — and wipe the whole board for a +2000 perfect-clear bonus.",
        ],
        "controls": "Tap / click only — no dragging, fully one-handed. Keyboard: Space start/restart, P pause, M mute.",
        "faqs": [
            ("Is Neon Pop free?",
             "Yes — it runs entirely in your browser for free, with no download, account or payment. It is an original NeonPlay game."),
            ("Does it work on mobile?",
             "Yes — it is built for one-handed touch play: pure taps, zero dragging, and the board letterboxes to any screen size."),
            ("How do I score more in Neon Pop?",
             "Score per pop equals group size squared × 5, and consecutive pops within 2 seconds multiply it up to ×5. Keep a chain alive across big groups, and clear the entire board for +2000."),
            ("Does the game track me?",
             "No. Everything runs 100% locally in your browser; your best score never leaves your device."),
        ],
    },
    {
        "slug": "neon-nonogram",
        "play": "play/",
        "title": "Neon Nonogram — Free Online Picture Logic Puzzle (No Ads, No Guessing, Daily Puzzle)",
        "h1": "Neon Nonogram",
        "tagline": "Use the row and column number clues to fill cells and reveal hidden neon pixel art — 12 solver-verified puzzles you can finish by pure logic, plus a daily board.",
        "desc": "Free online nonogram (picross) puzzle: zero guessing, no ads, no timer. Fill cells by pure logic using row and column clues, reveal neon pixel art, collect all 12 gallery pictures and come back for the daily board.",
        "emoji": "🕶️",
        "howto": [
            "Numbers beside each row and column tell you the runs of filled cells — '2 1' means a block of 2, then a gap, then a single.",
            "Tap a cell to fill it, tap again to mark a cross (definitely empty), tap again to clear.",
            "Fill every correct cell to reveal the hidden pixel art — wrong cells flash red on check and can be fixed.",
            "Solve puzzles to grow your gallery, and come back daily for the featured board — same picture for everyone.",
        ],
        "controls": "Tap cells to cycle fill / cross / clear. Keyboard: arrows + Space cycle, X marks a cross, Enter checks.",
        "faqs": [
            ("What is Neon Nonogram?",
             "A free picture-logic puzzle: use the row and column number clues to fill cells and reveal hidden neon pixel art. No download, no account, plays in any browser."),
            ("Do I ever need to guess?",
             "Never. All 12 puzzles are solver-verified to be solvable by pure logic, step by step — a fairness promise most nonogram apps can't make."),
            ("Is it really ad-free?",
             "Yes. No interstitials, no energy systems, no paywalls; your gallery progress saves automatically in your browser."),
            ("Can I play on mobile?",
             "Yes: big touch-friendly cells, three-tap marking (fill / cross / clear), full keyboard support on desktop, and a new daily picture every day."),
        ],
    },
    {
        "slug": "sudoku",
        "play": "play/",
        "title": "Sudoku Online Free — Daily Sudoku Puzzle (No Ads, Works Everywhere)",
        "h1": "Sudoku",
        "tagline": "Classic sudoku with a fresh seeded puzzle every day — easy, medium and hard. Conflict highlighting, no timer pressure, no forced ads. Progress saves in your browser.",
        "desc": "Play sudoku free online: three difficulties, a new seeded daily board identical for everyone, conflict highlighting and keyboard support. No download, no account, no forced ads — your progress saves automatically.",
        "emoji": "🔢",
        "howto": [
            "Fill the 9×9 grid so every row, column and 3×3 box contains the digits 1-9 exactly once.",
            "Tap a cell, then tap a number on the keypad — conflicts with the same row, column or box highlight instantly.",
            "Choose Easy, Medium or Hard; the Daily board gives every player worldwide the same seeded puzzle.",
            "Stuck cells can be cleared and re-filled — there is no timer and no penalty for experimenting.",
        ],
        "controls": "Tap a cell then a number. Keyboard: arrows move, 1-9 fill, Backspace clears.",
        "faqs": [
            ("What is Sudoku?",
             "A classic logic puzzle: fill the 9×9 grid so every row, every column and every 3×3 box contains the digits 1 to 9 exactly once. It is pure deduction — no math and no guessing required."),
            ("Is there a daily sudoku?",
             "Yes. The Daily board is generated from the date, so every player worldwide gets the same puzzle each day. Easy, Medium and Hard free-play modes are always available too."),
            ("Are the puzzles always solvable?",
             "Yes — every board is generated from a complete valid solution, so a solution always exists. Conflicts with existing numbers are highlighted the moment you place a digit."),
            ("Does it cost anything or show ads?",
             "It is completely free with no forced ads, no accounts and no downloads. Your current board saves automatically in your browser."),
        ],
    },
    {
        "slug": "neon-hoops",
        "play": "play/",
        "title": "Neon Hoops — Free Basketball Shooting Game with Daily Wind Challenge",
        "h1": "Neon Hoops",
        "tagline": "Flick basketball with real wind — drag to shoot, correct your arc like in golf, chain swishes for combo points and climb from Bronze to Legend in 60-second runs.",
        "desc": "Play Neon Hoops free online: a 60-second flick basketball arcade game with wind-adjusted trajectories, 8-dot aim preview, swish combos, seven ranks from Bronze to Legend and a Daily challenge where every player worldwide shoots the same wind. No download, no account.",
        "emoji": "🏀",
        "accent": "#ff9e40",
        "howto": [
            "Drag back from anywhere on the court and release to flick the ball — the dotted preview shows the first half of your arc.",
            "Read the flag: each shot has a horizontal wind that pushes your ball mid-flight, so aim upwind like in golf.",
            "Swishes (no rim, no board) score 3, normal makes 2, and every consecutive make adds +1 combo bonus up to +5.",
            "Play the Daily challenge for a seeded wind pattern and hoop placement that is identical for everyone each day.",
        ],
        "controls": "Drag with mouse or touch to flick. Keyboard: arrows set angle/power, Space shoots, R restarts, M mutes.",
        "faqs": [
            ("What is Neon Hoops?",
             "A free 60-second arcade basketball game: drag to flick the ball, read the wind, chain swishes, and climb from Bronze to Legend. No download, no account."),
            ("How does the wind work?",
             "Each shot has a horizontal wind shown by the flag; your ball drifts with it, so you adjust your arc like in golf. In the Daily challenge the whole wind pattern is identical for players worldwide."),
            ("Is there a daily challenge?",
             "Yes — a seeded course (wind + hoop movement) that's the same for everyone each day, with streak tracking and a monthly mulligan so one busy day won't break your run."),
            ("Can I play on mobile?",
             "Yes: flick with one finger on touch screens, full mouse support, and an angle/power keyboard mode on desktop. Progress saves on your device and shares as a card in one tap."),
        ],
    },
    {
            "slug": "neon-solitaire",
            "play": "play/",
            "title": "Play Solitaire Free Online — No Ads, Klondike + Daily Challenge",
            "h1": "Neon Solitaire",
            "tagline": "Classic Klondike solitaire in neon: drag or tap cards, double-click sends them home, undo anything — plus a daily challenge with the same deal for everyone and a 🔥 streak to keep alive.",
            "desc": "Play solitaire free online, no ads and no sign-up: full Klondike rules (draw 1, unlimited recycles), drag or tap-to-move on any device, double-tap auto-finish, unlimited undo, hints and standard scoring. A daily challenge deals the exact same seeded board worldwide to feed your 🔥 streak, and random deals are endless.",
            "emoji": "🃏",
            "accent": "#00e5ff",
            "howto": [
                "Move cards onto the seven tableau columns in descending order with alternating colors — red on black, black on red. Only kings land on empty columns.",
                "Build the four foundations up from Ace to King, one suit each. Double-click or double-tap a card to send it home automatically.",
                "Tap the stock to draw one card; when it runs out, tap again to recycle the waste and keep going. Every deal stays winnable through unlimited recycles.",
                "Finish fast for a time bonus and star rating; the Daily tab deals the same seeded board to every player worldwide and grows your 🔥 streak.",
            ],
            "controls": "Drag cards, or tap a card then its destination. Double-click/double-tap auto-plays to foundations. Keyboard: Tab/arrows move, Enter select/place, U undo, D draw, H hint, A auto-finish.",
            "faqs": [
                ("Is this real Klondike solitaire?",
                 "Yes — seven tableau columns, four foundations built A to K by suit, descending alternating-color stacking, kings on empty columns, draw-one stock with unlimited recycles: the full classic ruleset, nothing simplified."),
                ("Is it free with no ads in the game?",
                 "Completely free: no interstitials, no energy timers, no account. Ads never interrupt a deal — your streak, best score and settings save locally in your browser."),
                ("What is the daily challenge and the 🔥 streak?",
                 "Every UTC day the Daily tab deals one seeded board identical for every player worldwide. Clear it and your 🔥 streak grows — miss a day and it resets, so come back tomorrow."),
                ("Can I play on mobile?",
                 "Yes — big touch targets, drag or tap-to-move (no precise dragging needed), double-tap auto-play, and the board scales to fit any phone screen without scrolling."),
            ],
        },
    {
            "slug": "neon-fairway",
            "play": "play/",
            "title": "Play Golf Solitaire Free Online — No Ads, with Daily Deals & Jokers",
            "h1": "Neon Fairway",
            "tagline": "Golf solitaire with a Balatro twist — pick 1 of 3 opening Jokers, sweep the 35-card fairway by playing ±1 ranks onto the pile, and ride chain multipliers up to ×7.5 on the world's same daily deal.",
            "desc": "Play golf solitaire free online, no ads: clear the 35-card field by playing cards one rank above or below the waste pile, pick an opening Joker (Wraparound A-K, Chain Master, Deep Stock), chain plays for up to ×7.5 score multipliers and play the daily deal that is identical worldwide. No download, no account.",
            "emoji": "⛳",
            "accent": "#39ff88",
            "howto": [
                "Pick 1 of 3 opening Jokers — rule modifiers like Wraparound (A and K connect) or Chain Master (multiplier cap ×7.5) that reshape the same deal.",
                "Tap any glowing card whose rank is one above or below the waste pile's top card — it flies onto the pile; if nothing fits, tap a stock pile to flip.",
                "Every consecutive play without flipping stock grows your chain multiplier (×1 → ×5, or ×7.5 with Chain Master); flipping stock resets it — plan the longest route.",
                "Clear all 35 cards for a +500 bonus (+20 per unflipped stock card) and climb from Bronze to Legend; the Daily deal deals the exact same cards worldwide every day.",
            ],
            "controls": "Tap cards or stock piles (mouse/touch). Keyboard: Tab/arrows select cards, Enter plays, D flips stock, R restarts, M mutes.",
            "faqs": [
                ("What is Neon Fairway?",
                 "A free golf solitaire: clear the 35-card field by playing cards one rank above or below the pile, chain plays for score multipliers, and pick an opening Joker that bends the rules. No download, no account."),
                ("What are Jokers?",
                 "Each round starts with a pick of 1 from 3 rule modifiers — like Wraparound (A and K connect) or Chain Master (multiplier cap rises to ×7.5). The same deal plays differently with each build."),
                ("Is there a daily deal?",
                 "Yes: one seeded deal with its own Joker choices, identical worldwide every day. Your best score goes on the board with streak tracking and a monthly streak-protect card."),
                ("Can I play on mobile?",
                 "Yes: tap cards to play, full keyboard support on desktop, no download or account — progress and best scores save automatically on your device."),
            ],
        },
    {
            "slug": "neon-link",
            "play": "play/",
            "title": "Play Onet Connect Free Online — Mahjong Link Tile Matching Game (Daily Board, No Ads)",
            "h1": "Neon Link",
            "tagline": "The classic connect-2 tiles puzzle (Onet / Mahjong Link style): match two identical tiles and link them with a path of at most 2 turns — every board is mathematically guaranteed clearable.",
            "desc": "Play Onet Connect free online: a Mahjong Link style matching puzzle. Tap two identical tiles and they clear if a path with at most 2 turns links them, even around the outside of the board. Combo scoring, hints, a global daily board, ranks from Bronze to Legendary and streak tracking. No download, no ads.",
            "emoji": "🔗",
            "accent": "#ffd54a",
            "howto": [
                "Tap two matching tiles: if a connecting line with at most 2 turns exists — through empty space or around the outside of the board — they clear with a neon flash.",
                "Clear pairs within 3 seconds of each other to build a combo multiplier up to ×2.5; finish fast for up to +300 time bonus.",
                "Stuck? 3 hints per board highlight a linkable pair, and the board auto-shuffles (−100 points) only if no link exists — which the generator makes almost never happen.",
                "Play the Daily board: one seeded layout per day, identical worldwide, with clear-time ranks from Bronze to Legendary and a streak with a monthly make-up card.",
            ],
            "controls": "Tap / click two matching tiles. Keyboard: arrows move, Enter select, H hint, S shuffle, M mute.",
            "faqs": [
                ("What is Neon Link?",
                 "A free connect puzzle in the Onet / Mahjong Link style: tap two matching tiles and they clear if a path with at most 2 turns links them — paths can go around the outside of the board. No account, plays in any browser."),
                ("Can a board ever be unsolvable?",
                 "No. Boards are generated with a repair-guaranteed algorithm: every board is verified to be fully clearable without shuffling, across hundreds of tested seeds."),
                ("Is there a daily board?",
                 "Yes: one seeded board per day, identical worldwide, with your clear time ranked from Bronze to Legendary, plus streak tracking and a monthly make-up card."),
                ("Does it work on mobile?",
                 "Yes: big tap targets, one-finger play, full keyboard support, and progress — best times, top 10, streaks — saves automatically on your device."),
            ],
        },
    {
            "slug": "tile-rush",
            "play": "play/",
            "title": "Tile Rush — Free Online Triple Tile Match Puzzle (Daily Puzzle, No Ads)",
            "h1": "Tile Rush",
            "tagline": "The sheep-game formula, minus the ads: tap stacked tiles into a 7-slot tray, match 3 identical to clear, and don't overflow — every deal is mathematically guaranteed solvable, with a daily board shared worldwide.",
            "desc": "Play Tile Rush free online: a triple tile match puzzle (tile master style) with layered stacks, a 7-slot tray and 3-of-a-kind matching. Every board is generated to be solvable, there's a seeded daily puzzle identical worldwide, endless mode, ranks, streaks and no ads or energy systems. No download, no sign-up.",
            "emoji": "🀄",
            "accent": "#00e5ff",
            "howto": [
                "Tap a tile that isn't buried — top-layer tiles glow cyan, buried ones are dimmed — and it flies into your 7-slot tray at the bottom.",
                "Collect 3 identical tiles in the tray and they burst away; clear every tile on the board to win the deal.",
                "If the tray fills all 7 slots without a match, the run is over — but the board stays the same, so retry the exact same deal and plan a better route.",
                "Each run grants one Pull-out (return up to 3 tray tiles to the board) and one Shuffle; score rewards speed and unused props.",
            ],
            "controls": "Tap / click tiles (top-most only). Keyboard: arrows move focus, Enter picks, 1 = Pull-out, 2 = Shuffle.",
            "faqs": [
                ("What is Tile Rush?",
                 "A free layered tile-matching puzzle: tap tiles into a 7-slot tray, match 3 identical to clear, and don't let the tray overflow. Every board is generated to be solvable — no dead deals."),
                ("Is there a daily puzzle?",
                 "Yes: a seeded board identical worldwide every day (the \"same wind, same board\" culture), track your streak with one free mulligan per month, and replay the same deal to beat your time."),
                ("Is it really free without ads?",
                 "Yes: no interstitials, no energy systems, no signup; unlimited play right in the browser, progress saved on your device."),
                ("What if I get stuck?",
                 "Each run includes one Pull-out (return up to 3 tray tiles to the board) and one Shuffle. Tip: keep the tray under 4 tiles and clear top layers first."),
            ],
        },
    {
            "slug": "neon-air-hockey",
            "play": "play/",
            "title": "Neon Air Hockey — Free 2-Player Air Hockey Game (Same Device + AI)",
            "h1": "Neon Air Hockey",
            "tagline": "One phone, two players: drag your mallet, slam the puck past your friend, first to 7 wins. Three AI levels to beat, a same-screen 2-player mode with true multi-touch, and a Daily AI challenge the whole world plays.",
            "desc": "Play air hockey online free: a neon table hockey game with true multi-touch 2-player on one device, three AI difficulty levels, first-to-7 matches, a Daily AI with the same seeded opponent worldwide, seven ranks from Bronze to Legend and one-tap score cards. No download, no account, no in-game ads.",
            "emoji": "🏒",
            "accent": "#00e5ff",
            "howto": [
                "Drag inside your half to swing your mallet — mallet speed transfers to the puck, so fast flicks fire hard shots and gentle touches block.",
                "The puck banks off every wall: use angles to open the goal mouth. First to 7 goals wins; the Daily challenge is first to 5.",
                "Play 2-player air hockey on one device: true multi-touch gives each player their own half — two thumbs, one phone, no arguments.",
                "Beat Easy, Normal and Hard AI to climb from Bronze to Legend; the Daily AI gets a new seeded personality every day, identical for every player worldwide.",
            ],
            "controls": "Drag with mouse or touch (multi-touch: each player owns their half). Keyboard: arrows move your mallet, WASD moves Player 2, Space serves, P pauses, M mutes.",
            "faqs": [
                ("What is Neon Air Hockey?",
                 "A free air hockey game in your browser: drag your mallet, slam the puck, first to 7 wins. Play vs AI or 2-player on the same screen."),
                ("Can two people play on one phone?",
                 "Yes! True multi-touch: each player drags their own mallet on their half, so both can play at once. No download, no account."),
                ("What is the Daily AI?",
                 "Every day the AI gets a new seeded personality (same worldwide). Beat it in a first-to-5 match and your goal differential goes on the board."),
                ("Is my progress saved?",
                 "Yes: wins, rank and daily results save automatically on your device; share your score card in one tap."),
            ],
        },
]