# -*- coding: utf-8 -*-
"""Game catalog for the /games/ section.

Each entry: slug, title, h1, desc (meta), tagline, emoji, howto, faqs,
controls. The playable build lives in engine/assets/games/<slug>/play(.html|/)
and is copied verbatim to docs/games/<slug>/play(...)/ — games are self-contained
and iframe-embedded into the landing page.
"""

GAMES = [
    {
        "slug": "neon-tide",
        "title": "Play Neon Tide — Free Online Neon Arcade Shooter",
        "h1": "Neon Tide",
        "tagline": "Ride the neon tide — a synthwave arcade shooter with procedural sound, waves of glowing enemies and boss pressure.",
        "desc": "Play Neon Tide free online: a synthwave neon arcade shooter with waves of glowing enemies, procedural music and endless escalating pressure. No download, no sign-up.",
        "emoji": "🌊",
        "accent": "#22d3ee",
        "play": "play/",  # directory build
        "howto": [
            "Move with the mouse or arrow keys — your ship follows on the lower half of the screen.",
            "Hold to fire; dodging matters as much as shooting because enemies return fire in patterns.",
            "Survive escalating waves, chase the score multiplier, and beat your personal best.",
        ],
        "controls": "Mouse / touch to move, hold to shoot. Keyboard: arrow keys.",
        "faqs": [
            ("Is Neon Tide free?",
             "Yes — it runs entirely in your browser for free, with no download, account or payment. It is an original game built by the NeonPlay team."),
            ("Does it work on mobile?",
             "Yes. The game auto-scales to any screen and supports touch: drag to move your ship, it fires automatically while you hold."),
            ("Who made Neon Tide?",
             "We did — it is an exclusive NeonPlay original, with every sound and effect generated in code (no asset files)."),
            ("Does the game track me?",
             "No. The game runs 100% locally in your browser; your scores never leave your device."),
        ],
    },
    {
        "slug": "snake",
        "title": "Play Snake Online — Free Classic Snake Game",
        "h1": "Snake",
        "tagline": "The timeless snake game: eat, grow, don't bite yourself. One more run is always one turn away.",
        "desc": "Play the classic Snake game free online. Arrow keys, WASD or swipe on mobile. Eat apples, grow longer, avoid your own tail — instant play, no download.",
        "emoji": "🐍",
        "accent": "#4ade80",
        "howto": [
            "Press any arrow key (or swipe on mobile) to start — the snake moves on its own once started.",
            "Steer into the red apples: every apple makes you one segment longer and raises your score.",
            "Avoid walls and your own tail — the game ends the moment you crash, then restart instantly.",
        ],
        "controls": "Arrow keys / WASD, or swipe on touch screens.",
        "faqs": [
            ("How do you win at Snake?",
             "Snake has no final win — you win by beating your high score. The classic technique is to coil in a spiral: keep your body along the edges so the center stays open for emergency turns."),
            ("Is this the same Snake as on old Nokia phones?",
             "Same game concept — eat, grow, don't crash. This version is an original browser implementation with smooth controls, mobile swipe support and instant restart."),
            ("Does it work on a phone?",
             "Yes — swipe anywhere on the board to steer. The board scales to fit any screen size."),
            ("Are my scores saved?",
             "Your best score is kept in memory while the tab is open; nothing is stored on our side or on your device after you leave."),
        ],
    },
    {
        "slug": "2048",
        "title": "Play 2048 Online — Free Number Puzzle Game",
        "h1": "2048",
        "tagline": "Slide, merge, double. A deceptively simple number puzzle that eats hours — reach the 2048 tile.",
        "desc": "Play 2048 free online. Swipe or use arrow keys to merge tiles and reach 2048. Original clean implementation, instant play, works on desktop and mobile.",
        "emoji": "🔢",
        "accent": "#fbbf24",
        "howto": [
            "Swipe or press arrow keys to slide every tile one step in that direction.",
            "When two tiles with the same number touch, they merge into one tile of double value.",
            "A new tile appears after each move — keep big numbers in one corner and build toward 2048.",
        ],
        "controls": "Arrow keys / WASD, or swipe on touch screens.",
        "faqs": [
            ("What is the 2048 world record?",
             "Reaching the 2048 tile is the classic goal; expert players keep going to 4096 and beyond. Scores above 20,000 are considered very strong; the theoretical maximum tile on a 4×4 board is 131,072."),
            ("What is the best strategy for 2048?",
             "Pick one corner and never move your biggest tile out of it — most players keep it bottom-right and only use three directions. Build a descending 'snake chain' of tiles so merges cascade."),
            ("Is this the original 2048?",
             "This is our own clean-room implementation of the 2048 rules (the game concept was created by Gabriele Cirulli in 2014). No ads inside the board, instant restarts."),
            ("Does it work offline?",
             "Yes — once the page has loaded, the game runs entirely in your browser with no connection needed."),
        ],
    },
    {
        "slug": "memory-pairs",
        "title": "Memory Pairs — Free Online Matching Card Game",
        "h1": "Memory Pairs",
        "tagline": "Flip, remember, match. The classic concentration card game — train your working memory in two minutes.",
        "desc": "Play Memory Pairs free online: the classic concentration matching game with 8 emoji pairs. Flip two cards, find all pairs in as few moves as you can.",
        "emoji": "🧠",
        "accent": "#c084fc",
        "howto": [
            "Click any card to flip it, then click a second one.",
            "If the two cards match, they stay face up; if not, they flip back after a moment.",
            "Remember what you saw — clear all 8 pairs in the fewest moves possible.",
        ],
        "controls": "Click / tap cards.",
        "faqs": [
            ("What is the fewest moves to win Memory Pairs?",
             "With 8 pairs and perfect memory, 8 moves (16 flips) is the theoretical minimum — every flip after the first pair of each turn must match. Typical casual wins land around 14–20 moves."),
            ("Does this game actually improve memory?",
             "Concentration-style games train visual working memory — the 'where did I see that' skill. Regular play improves your strategy (scanning in rows) and short-term recall."),
            ("Is it suitable for kids?",
             "Yes — no timers, no fail states, big friendly cards. It is a calm game; kids and grandparents play it the same way."),
            ("Can I play on a phone?",
             "Yes, tap cards directly — the board resizes to fit your screen."),
        ],
    },
    {
        "slug": "tic-tac-toe",
        "title": "Tic Tac Toe Online — Play Free vs Computer or a Friend",
        "h1": "Tic Tac Toe",
        "tagline": "X's, O's and one unbeatable robot. The three-in-a-row classic — now with a minimax AI you can actually beat (sometimes).",
        "desc": "Play Tic Tac Toe free online against a smart computer AI or a friend in 2-player mode. Instant play in your browser, works on desktop and mobile.",
        "emoji": "⭕",
        "howto": [
            "Tap any square (or press keys 1–9) to place your X — you always start.",
            "The computer replies instantly with strong play; line up three in a row — across, down or diagonally — to win.",
            "Switch to 2-player mode to pass and play with a friend on the same screen.",
        ],
        "controls": "Click / tap squares, or number keys 1–9.",
        "faqs": [
            ("Can you beat the computer at Tic Tac Toe?",
             "Our AI plays near-perfect minimax strategy with a small dose of randomness — it never falls for the classic double-threat traps, but it leaves the door open just often enough. About one in five games is winnable with sharp play."),
            ("Is Tic Tac Toe solved?",
             "Yes — with perfect play from both sides, Tic Tac Toe is always a draw. That's why the interesting question is spotting your opponent's mistake first, and why our AI deliberately isn't 100% perfect."),
            ("How do I always win Tic Tac Toe?",
             "Against imperfect opponents: take the center first, then create a fork — two threats at once. A fork forces a loss because your opponent can only block one line."),
            ("Is it free and private?",
             "Completely. The game runs in your browser with no sign-up, no ads inside the board, and nothing is uploaded — scores reset when you leave."),
        ],
    },
    {
        "slug": "breakout",
        "title": "Play Breakout Online — Free Brick Breaker Game",
        "h1": "Breakout",
        "tagline": "One ball, one paddle, a wall of glowing bricks — the arcade classic that never gets old.",
        "desc": "Play Breakout free online: smash every neon brick with one ball and a paddle you control by mouse, touch or keyboard. Level up, chase high scores, no download or sign-up.",
        "emoji": "🧱",
        "howto": [
            "Move the paddle with your mouse, finger or arrow keys — keep the ball alive.",
            "Launch with a tap, click or Space, then clear all six rows of bricks to advance.",
            "Each cleared wall starts a faster level; you get three lives per run, so aim carefully.",
        ],
        "controls": "Mouse / touch to move the paddle, tap or click to launch. Keyboard: arrow keys + Space.",
        "faqs": [
            ("Is Breakout free to play here?",
             "Yes — it runs entirely in your browser, no download, no account and no payment. It is an original NeonPlay implementation of the arcade classic."),
            ("Does Breakout work on a phone?",
             "Yes. Drag anywhere on the screen to slide the paddle and tap to launch — the board scales to any screen size in portrait or landscape."),
            ("What happens when I clear all the bricks?",
             "You advance to the next level: the ball gets faster and the wall resets. Your score carries over, and tougher two-hit bricks stay at the top rows."),
            ("How is my score calculated?",
             "Each brick is worth more in higher rows — up to 60 points per brick. Three lives per run, and your best runs come from keeping the ball angle steep and controlled."),
        ],
    },
    {
        "slug": "minesweeper",
        "title": "Play Minesweeper Online — Free Classic Mine Game",
        "h1": "Minesweeper",
        "tagline": "Ten mines, ninety-one tiles, zero room for luck. The logic puzzle that ate the 90s — reborn for your phone.",
        "desc": "Play the classic Minesweeper free online: 9x9 board with 10 mines, first click is always safe, tap to reveal and long-press to flag. No download, works on desktop and mobile.",
        "emoji": "💣",
        "howto": [
            "Tap a tile to reveal it — the first tap is always safe, and numbers show how many mines touch that tile.",
            "Long-press a tile (or right-click, or turn on flag mode) to mark mines you have deduced.",
            "Reveal every safe tile to win; hitting a single mine ends the run, so let logic lead.",
        ],
        "controls": "Tap / click to reveal, long-press or right-click to flag. Flag-mode button for precision play.",
        "faqs": [
            ("Is the first click in Minesweeper always safe?",
             "Yes — mines are placed after your first reveal, and the first tap plus its neighbors are guaranteed mine-free, so every game starts with a real opening."),
            ("How do I flag a mine on mobile?",
             "Press and hold a tile for about half a second, or tap the flag-mode button above the board and then tap tiles — both mark or unmark a suspected mine."),
            ("What do the numbers mean in Minesweeper?",
             "A number tells you exactly how many of the eight surrounding tiles hide a mine. Cross-referencing overlapping numbers is how you deduce which tiles are safe."),
            ("Is this Minesweeper free and private?",
             "Completely free with no sign-up. Everything runs locally in your browser — your games, times and flags never leave your device."),
        ],
    },
    {
        "slug": "flappy-dash",
        "title": "Play Flappy Dash Online — Free One-Tap Flying Game",
        "h1": "Flappy Dash",
        "tagline": "One tap to fly, one touch to die. Thread the neon gates and chase your best through a synthwave skyline.",
        "desc": "Play Flappy Dash free online: a one-tap neon flying arcade game. Guide your glider through endless gates with perfect timing. Instant play on desktop and mobile, no download.",
        "emoji": "🚀",
        "howto": [
            "Tap the screen, click, or press Space to flap — each tap gives one upward boost against gravity.",
            "Thread the glowing gates: every gate you pass is one point, and gaps tighten as your score climbs.",
            "One touch of a gate or the ground ends the run — find your rhythm and chase your best score.",
        ],
        "controls": "Tap / click / Space to flap. That's the whole game — mastery is timing.",
        "faqs": [
            ("Is Flappy Dash free?",
             "Yes — it runs entirely in your browser with no download, account or payment. It is an original NeonPlay arcade game with procedurally drawn neon visuals."),
            ("Why is Flappy Dash so hard?",
             "By design: gravity is constant and each tap is a fixed boost, so success is pure rhythm. Gaps shrink as your score rises, keeping every run tense."),
            ("Does it work on mobile?",
             "Yes — tap anywhere on the screen to flap. The game scales to any screen and runs at full speed on modern phones."),
            ("Is my best score saved?",
             "Your best score is kept for the session so you can chase it immediately. Nothing is stored on our servers — gameplay stays on your device."),
        ],
    },
    {
        "slug": "brickstorm",
        "title": "Play Brickstorm — Free Neon Brick Breaker Roguelite with Upgrades",
        "h1": "Brickstorm",
        "tagline": "Catch balls, smash brick waves, pick upgrades — Breakout meets Vampire Survivors in this neon roguelite.",
        "desc": "Play Brickstorm free online: a neon brick-breaker roguelite with upgrade builds, infinite waves and combo scoring. One-tap controls on desktop and mobile, no download.",
        "emoji": "🧱",
        "howto": [
            "Move the paddle left and right to catch falling balls — they auto-launch upward.",
            "Smash the advancing brick wall to earn XP; bricks glow brighter as their HP increases.",
            "Collect XP orbs to level up and choose one of three random upgrades that stack for the run.",
        ],
        "controls": "Drag / arrow keys / AD to move the paddle. Balls auto-launch — just position and survive.",
        "faqs": [
            ("What is Brickstorm?",
             "A free browser roguelite that fuses brick-breaker physics with Vampire-Survivors-style upgrade builds. Catch balls, smash waves of neon bricks, and pick from three random upgrades each level."),
            ("How do upgrades work?",
             "Destroyed bricks drop XP orbs that auto-attract to your paddle. Fill the XP bar and the game pauses, offering three random upgrades — multiball, damage, speed, pierce or wider paddle — that stack for the rest of the run."),
            ("Can I play Brickstorm on mobile?",
             "Yes. Touch-drag to move the paddle, fully responsive canvas, no download or sign-up needed. Keyboard (arrow keys / AD) and mouse also supported on desktop."),
            ("What's the best upgrade strategy?",
             "Most players take Multiball first (each ball deals full damage), then Damage or Pierce. Keep your combo alive by hitting brick clusters quickly — the multiplier caps at 3×."),
        ],
        "variants": [
            {
                "kw_slug": "ball-x-pit-browser-alternative",
                "title": "Ball x Pit Browser Alternative — Brickstorm (Free, No Download)",
                "desc": "Looking for a Ball x Pit browser alternative? Brickstorm mixes survival breakout waves with roguelite level-up picks — free, no download, no account.",
                "intro": [
                    "Ball x Pit welded pinball-style ball physics to roguelite progression and became the game everyone wants to play one more run of. Brickstorm takes the same addictive skeleton — balls that keep hitting, bricks that keep coming, levels that let you stack power — and rebuilds it natively for the browser, so the run starts the second the page loads instead of the second your download finishes.",
                    "The loop reads like a love letter to Ball x Pit fans: a relentless cascade of numbered brick waves pushes down toward your paddle, every broken brick drops XP orbs for you to catch, and each level-up deals a three-card choice — MULTIBALL to flood the screen, DAMAGE to punch through tanky rows, PIERCE to tunnel through clusters, PADDLE to widen your catch, SPEED to make everything reckless. A combo multiplier (up to 3×) rewards players who keep chains alive instead of sniping single bricks.",
                    "Where Brickstorm differs is friction, not depth: there is nothing to install, nothing to launch, no account wall and no paywall — it is a single HTML page with the whole game in it. It runs on the same cheap laptop you have open for work, it supports touch and keyboard on the same screen, and the interface ships in English and Chinese. If your appetite for Ball x Pit outlived your patience for its install queues, this is the five-minute fix.",
                ],
                "faqs": [
                    ("Is Brickstorm really free like Ball x Pit?",
                     "Yes — completely free with no account, no download and no paywall. The whole game is one web page: open it, tap a mode and play. There are no energy systems or timers gating your runs."),
                    ("How is Brickstorm different from Ball x Pit?",
                     "Ball x Pit adds ball fusion and an inventory meta between runs; Brickstorm keeps the survival-breakout core — descending waves, XP orbs, three-card level-up picks, a combo multiplier — as a pure browser experience with zero install friction. Think of it as the same genre itch in a smaller, instant-loading package."),
                    ("Does it work on a phone or a school laptop?",
                     "Both. The game auto-scales to any screen, supports swipe and drag on touch, and because everything runs locally in the browser it performs fine on low-end hardware and locked-down machines with nothing but a browser installed."),
                ],
            },
            {
                "kw_slug": "games-like-ball-x-pit-free",
                "title": "Games Like Ball x Pit (Free, In Your Browser) — Brickstorm & More",
                "desc": "Free browser games like Ball x Pit: merge-driven Brickstorm, classic Breakout, merge-puzzle 2048 and the idle ball-builder Idle Neon Breaker — all instant-play.",
                "intro": [
                    "If Ball x Pit hooked you, what you actually fell for is a stack of three overlapping pleasures: balls that keep flying, numbers that keep growing, and builds that feel smarter every run. The good news is that a browser is enough to chase all three — no storefront, no download queue, no GPU requirement. Here is what to play, all free on this site.",
                    "Brickstorm is the closest match: a survival breakout where waves descend and never stop, XP orbs drop from every break, and each level-up offers a three-card roguelite pick (multiball, pierce, damage, paddle width, ball speed). A combo multiplier up to 3× punishes passive play. Idle Neon Breaker takes the ball-builder fantasy in the opposite direction — balls bounce by themselves, bricks merge 2048-style and double on a timer, and your offline earnings accumulate at full rate with no cap while the tab is closed.",
                    "For the number-growth side of Ball x Pit, the site 2048 is the reset-your-brain classic, and Breakout covers the pure paddle-and-ball ancestor. All four games run on the same engine philosophy: one page, instant load, English and Chinese, no accounts. Bookmark the hall page — new games are added regularly and land in the RSS feed the day they ship.",
                ],
                "faqs": [
                    ("What games are similar to Ball x Pit but free?",
                     "Brickstorm (survival breakout with roguelite upgrades) is the nearest free match here; Idle Neon Breaker covers the ball-builder side with 2048-style merges, and classic Breakout and 2048 round out the number-growth itch. Every one of them loads instantly in a browser tab."),
                    ("Can I play without installing anything?",
                     "Yes. Each game is a self-contained web page — there is no launcher, no download and no plug-in. You can close the tab mid-run on Brickstorm, or leave Idle Neon Breaker running to farm offline earnings."),
                    ("Do these games work on mobile?",
                     "They are built mobile-first: touch targets are sized for thumbs, the boards scale to the screen, and Brickstorm paddle follows your finger. Desktop keyboards work too — arrow keys steer every paddle game."),
                ],
            },
            {
                "kw_slug": "vampire-survivors-breakout-online",
                "title": "Vampire Survivors-Style Breakout Online — Brickstorm Survival Waves",
                "desc": "The auto-attack survival loop, rebuilt as a breakout: balls that never stop, descending waves, and a three-card build choice on every level-up. Free in your browser.",
                "intro": [
                    "Vampire Survivors defined a genre by automating the shooting and keeping only the decisions: steer your character, vacuum the XP, and pick the upgrade that turns your build monstrous. Brickstorm applies exactly that philosophy to a paddle game. Your ball is the auto-attack — it never stops moving and never asks you to press a fire button. Your paddle is the character — positioning is the entire skill expression. The descending brick waves are the swarm.",
                    "The survival loop maps one-to-one: bricks shatter into glowing XP orbs that drift toward your paddle; catch enough and you level up, pausing the chaos for a three-card choice — flood the screen with MULTIBALL, punch through armor with DAMAGE, or thread clusters with PIERCE. Meanwhile a timer pushes new waves down every eight seconds, so the board steadily thickens like a survivors minute count climbing. A combo multiplier rewards the moment your build comes online and starts clearing screens instead of bricks.",
                    "Runs are tuned for browser-sized sessions: three lives, an escalation that reaches dense multi-row waves, and a game-over screen that tracks your best wave and score against your own record. It is the survivors fantasy compressed into a tab that is already open — no download, English or Chinese, touch or keyboard.",
                ],
                "faqs": [
                    ("Is Brickstorm really like Vampire Survivors?",
                     "Structurally yes: automatic attacks (the bouncing ball), XP you collect for level-ups, three-choice upgrade drafting, escalating waves and a combo economy that rewards snowballing. The skill layer swaps character steering for paddle positioning."),
                    ("How long is a run?",
                     "Most runs last a few minutes — the wave pressure ends them quickly if your build falls behind. The HUD tracks your best wave and best score locally, so the natural loop is one more run to beat your own record."),
                    ("What upgrades can I pick?",
                     "Each level-up offers three of: MULTIBALL (extra ball), DAMAGE +1, SPEED +20%, PIERCE (hit through extra bricks), and PADDLE +25% width. Stacking them is where runs go from survival to screen-clearing."),
                ],
            },
        ],    },
    {
        "slug": "neon-block-jam",
        "title": "Play Neon Block Jam — Free Color Block Puzzle (No Timer)",
        "h1": "Neon Block Jam",
        "tagline": "Slide neon blocks through matching color gates — no timer, no lives, just pure puzzle zen with unlimited undo.",
        "desc": "Play Neon Block Jam free online: a relaxing color block sliding puzzle with 10 levels, unlimited undo and no timer. Slide neon blocks through matching gates — instant play on desktop and mobile.",
        "emoji": "🟦",
        "howto": [
            "Tap a block to select it, then drag along its axis to slide — it snaps to the grid one cell at a time.",
            "Blocks can only exit through their matching color gate on the outer wall; different-colored blocks block the gate.",
            "Clear every block from the board to win. Finish at or under par moves for 3 stars, with unlimited free undo.",
        ],
        "controls": "Tap / click to select, drag to slide. Keyboard: arrow keys to move cursor, Enter to confirm. U = undo, R = reset.",
        "faqs": [
            ("Is there a timer in Neon Block Jam?",
             "No — deliberately timer-free with unlimited free undo. The only score is a move count vs par for stars, so you can think as long as you want without anxiety."),
            ("How do the color gates work?",
             "Each gate on the outer wall has a color. A block of the same color can pass through and vanish. Blocks of any other color are blocked by the gate wall — that's the puzzle: figure out the right order."),
            ("Can I play on my phone?",
             "Yes. Touch-drag controls, responsive layout, works in any modern browser. No download, no sign-up, no ads interrupting your puzzle."),
            ("How do I get 3 stars on a level?",
             "Finish at or under par moves. Tip: clear the blocks that block other blocks' gates first, and keep the center of the board open as long as possible."),
        ],
    },

    {
        "slug": "connect-four",
        "title": "Play Connect Four Online — Free Strategy Board Game vs AI",
        "h1": "Connect Four",
        "tagline": "Drop discs, build a line of four, block your opponent — the classic strategy game reimagined with neon visuals and a built-in AI.",
        "desc": "Play Connect Four free online against a smart AI or a friend. Drop discs to build four in a row — horizontal, vertical or diagonal. No download, instant play.",
        "emoji": "🔴",
        "howto": [
            "Click any column to drop your disc — red discs are yours, the AI plays pink.",
            "Build a line of four (horizontal, vertical or diagonal) before the AI does.",
            "Block the AI's attempts while building your own threat — think two moves ahead.",
        ],
        "controls": "Click / tap a column to drop your disc. The AI responds instantly.",
        "faqs": [
            ("Is Connect Four free to play here?",
             "Yes — it runs entirely in your browser with no download, account or payment. Play against our built-in AI or pass-and-play with a friend."),
            ("How does the AI work?",
             "Our AI checks for immediate wins and blocks your threats, with a touch of randomness to keep games interesting. It plays a strong but beatable game."),
            ("Can I play with a friend?",
             "Yes — switch to 2-player mode to pass and play on the same screen. Red and blue discs alternate turns."),
            ("What's the best opening move?",
             "The center column is statistically the strongest — it participates in more potential lines than any other column."),
        ],
    },
    {
        "slug": "idle-neon-breaker",
        "play": "play/",
        "title": "Idle Neon Breaker — Idle Brick Breaker with 2048 Merges (No Forced Ads)",
        "h1": "Idle Neon Breaker",
        "tagline": "An idle brick breaker where numbered bricks merge 2048-style and double while you watch — balls bounce and break on their own, offline progress is unlimited, and there are no forced ads.",
        "desc": "Free browser idle game: balls bounce and break numbered bricks on their own; bricks merge 2048-style and double over time; buy ball, damage, speed and coin upgrades and chase your highest brick. Full offline progress with no cap, autosave, no accounts, no forced ads.",
        "emoji": "💫",
        "howto": [
            "Balls bounce by themselves and damage bricks — each hit lowers a brick's number; at 0 it shatters into coins.",
            "Every 20 seconds bricks merge 2048-style: equal numbers combine and double (2+2→4, 4+4→8).",
            "Spend coins in the shop: more balls, more damage per hit, faster balls, bigger coin payouts.",
            "Close the tab any time — your coins keep earning at full rate offline, with no cap. Come back and claim.",
        ],
        "controls": "Zero controls required — the game plays itself. Tap the shop cards to buy upgrades.",
        "faqs": [
            ("What is Idle Neon Breaker?",
             "A free browser idle game: balls bounce and break numbered bricks on their own; bricks merge 2048-style and double over time; you buy upgrades and watch numbers explode. It runs in any browser — no download, no account."),
            ("Does it earn while I'm away?",
             "Yes. Offline progress is full-rate with no cap — close the tab, come back, claim everything at once. No 'come back every 2 hours' nonsense."),
            ("Are there forced ads or paywalls?",
             "No forced ads, ever. No accounts, no paywalls; progress saves automatically in your browser via localStorage."),
            ("What's the goal?",
             "Grow your highest brick: 2 → 4 → 8 → 16 and beyond. Keep firepower ahead of the merges and chase the record."),
        ],
    },
    {
        "slug": "neon-alchemy",
        "play": "play/",
        "title": "Neon Alchemy — Free Element Combining Game with Daily Puzzle (No AI, Works Everywhere)",
        "h1": "Neon Alchemy",
        "tagline": "Combine Water, Fire, Earth and Electric to discover 42 neon elements — from Steam to Cyberpunk. Handcrafted recipes, a daily global puzzle, zero AI, instant load.",
        "desc": "Free browser element-combining game: start with Water, Fire, Earth and Electric, discover 42 neon elements with handcrafted recipes, and take on the daily global puzzle board. No AI, no download, no account, progress saves automatically.",
        "emoji": "🧪",
        "howto": [
            "Tap two element chips to combine them — Water + Fire becomes Steam, and 38 handcrafted recipes lead from the basics to Cyberpunk.",
            "Every discovery unlocks new combinations and fills your collection wall — track your progress out of 42 elements.",
            "Take the daily puzzle: one handcrafted board per day, identical worldwide — reach the target element using only the limited pool.",
            "Your discoveries save automatically. Reset the collection any time for a fresh one-run challenge.",
        ],
        "controls": "Tap or click two element chips to combine. Keyboard: Tab + Enter works too.",
        "faqs": [
            ("What is Neon Alchemy?",
             "A free browser crafting game: combine Water, Fire, Earth and Electric to discover 42 neon elements, from Steam to Cyberpunk. No download, no account, and it loads instantly on any device."),
            ("Is there a daily challenge?",
             "Yes. One handcrafted puzzle board per day, identical for everyone worldwide, with a shareable result — Wordle-style. Boards rotate by date and limit which elements you can use."),
            ("Does it use AI like Infinite Craft?",
             "No. All recipes are handcrafted and built-in, so it loads instantly, works on school or office networks, and no discovery is ever wrong or random."),
            ("Is my progress saved?",
             "Yes. Your collection and daily completions save automatically in your browser via localStorage. You can reset the collection from inside the game for a fresh start."),
        ],
    },
]